# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kke7FavaOJXqL1qgfyPgLhd9BUTU3Saj
"""

import pandas as pd

df=pd.read_csv('/content/train.csv')
df